### ISSUE TITLE
Cargo run works but opening the server at localhost:8080 produces an errror

### ISSUE THREAD

**Issue by TristanStreich** [CarterMcClellan/Rustiator#1]
<img width="1523" alt="Screenshot 2024-01-02 at 10 01 08 PM" src="https://github.com/CarterMcClellan/Rustiator/assets/33437952/468cbac7-731f-4eb5-abba-a1bb6a48d59c">

**Comment by CarterMcClellan** [comment]
I was able to re-produce this error, I believe that the command 
```
open localhost:8000
```

Is ambiguous w.r.t what service should be used to open this address. Can you try specifying the application like so
```
open -a "Google Chrome" http://localhost:8080
```

Additionally, I've updated the codebase to simply open the browser automatically to the right host and port when you start the server :)

**Comment by tStreichenberger** [comment]
Awesome the browser opened automatically and it worked now!

**Comment by CarterMcClellan** [comment]
Nice!
